### ISSUE TITLE
Объявляйте переменные ближе к контексту использования

### ISSUE THREAD

**Issue by coursar** [pentogono/Tinkoff-bonus#4]
https://github.com/pentogono/Tinkoff-bonus/blob/2977b9d7f41ee9be9c577e10ab2fc6ac0950c3c4/src/main/java/ru/itpark/CashbackService.java#L12

Должно быть ```int totalCashback = ...```

**Comment by pentogono** [comment]
@coursar 
12f1b9455ebaa2f72408d46d4144e66d35ecfdd6
