### ISSUE TITLE
Нельзя один раз в конце разделить на hundredPercent?

### ISSUE THREAD

**Issue by coursar** [pentogono/Tinkoff-bonus#5]
https://github.com/pentogono/Tinkoff-bonus/blob/2977b9d7f41ee9be9c577e10ab2fc6ac0950c3c4/src/main/java/ru/itpark/CashbackService.java#L12-L14

**Comment by pentogono** [comment]
Можно, если сначало умножить процент кешбека с суммой покупки, потом просуммировать все покупки и в конце только разделить, то мы получим неверный результат.
Т.к. в условиях кешбека написано, что кешбек возвращается от целых 100 рублей покупки. Если сначало умножить (например на 5,30%) а потом разделить на 100, то получится, что результат будет завышенный. 
354/100=3 и затем 3*30=90
354*30=10620 и затем 10620/100=106
